language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - 8
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
after_success:
  - yarn run semantic-release
branches:
  only:
    - master
