language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - 8
after_success:
  - npx codecov
  - npx -p semantic-release@8 -c "semantic-release-pre && npm publish && semantic-release-post"
branches:
  except:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
