sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - 6
  - 8
before_script:
  - npm prune
script:
  - npm t
after_success:
  - npm run semantic-release
